#version de docker-compose
version: '3'
services:
  flask_app: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005" 
    volumes:
      - .:/PIT_STOP-BLOG
    env_file:
      - .env
    depends_on:
      - mysql_db
    container_name: flask_app

  mysql_db:
    image: mysql:5.7  # Use the official MySQL 5.7 image from Docker Hub
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Set the root password for MySQL
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # Create a database named 'mydatabase'
      MYSQL_USER: ${MYSQL_USER} # Create a MySQL user 'myuser'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Set the password for 'myuser'
    ports:
      - "3307:3306"  # Map host port 3306 to container port 3306 for MySQL
    command: --init-file /docker-entrypoint-initdb.d/create_schema.sql
    restart: always  # Restarts the MySQL container if it stops or crashes
    container_name: ${MYSQL_CONTAINER_NAME}
    volumes:
      - ./.data/db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/


volumes:
  db_data: